name: Tests

on:

  # On which repository actions to trigger the build.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:

      # Run all jobs to completion (false), or cancel
      # all jobs once the first one fails (true).
      fail-fast: false

      # Define a minimal test matrix, it will be
      # expanded using subsequent `include` items.
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

        include:
          - os: "ubuntu-latest"
            python-version: "3.7"
          - os: "ubuntu-latest"
            python-version: "3.8"
          - os: "ubuntu-latest"
            python-version: "3.9"
          - os: "ubuntu-latest"
            python-version: "3.10"
          - os: "ubuntu-latest"
            python-version: "3.11"
          - os: "ubuntu-latest"
            python-version: "3.12"

    defaults:
      run:
        shell: bash

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:

    - name: Acquire sources
      uses: actions/checkout@v3

    - name: Install prerequisites (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pip'
        cache-dependency-path: |
          setup.py
          requirements.txt
          dev-requirements.txt

    - name: Install project dependencies (Baseline)
      run: |
        pip install -r requirements.txt -r dev-requirements.txt

    # Install package in editable mode,
    # and run project-specific tasks.
    - name: Setup project
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --editable=.

    - name: Run tests
      run: |
        pytest
